export const PROJECTS_LOADED = 'PROJECTS_LOADED'; 
export const PROJECTS_ADD_CREATED = 'PROJECTS_ADD_CREATED'; 
export const PROJECTS_SET_UPDATED = 'PROJECTS_SET_UPDATED'; 
 
export const PROJECT_LOADED = 'PROJECT_LOADED'; 
export const PROJECT_CREATED = 'PROJECT_CREATED';  
export const PROJECT_UPDATED = 'PROJECT_UPDATED'; 
export const PROJECT_RESET = 'PROJECT_RESET'; 

export const CLIENTS_LOADED = 'CLIENTS_LOADED'; 
export const CLIENTS_ADD_CREATED = 'CLIENTS_ADD_CREATED'; 
export const CLIENTS_SET_UPDATED = 'CLIENTS_SET_UPDATED';
export const CLIENTS_SUPPLIER_LOADED = 'CLIENTS_SUPPLIER_LOADED';
export const CLIENTS_SUPPLIER_FILE_CREATED = 'CLIENTS_SUPPLIER_FILE_CREATED';

export const CLIENT_LOADED = 'CLIENT_LOADED'; 
export const CLIENT_CREATED = 'CLIENT_CREATED';  
export const CLIENT_UPDATED = 'CLIENT_UPDATED'; 
export const CLIENT_RESET = 'CLIENT_RESET'; 

export const SUPPLIERS_LOADED = 'SUPPLIERS_LOADED'; 
export const SUPPLIERS_ADD_CREATED = 'SUPPLIERS_ADD_CREATED'; 
export const SUPPLIERS_SET_UPDATED = 'SUPPLIERS_SET_UPDATED'; 

export const SUPPLIER_LOADED = 'SUPPLIER_LOADED'; 
export const SUPPLIER_CREATED = 'SUPPLIER_CREATED';  
export const SUPPLIER_UPDATED = 'SUPPLIER_UPDATED'; 
export const SUPPLIER_RESET = 'SUPPLIER_RESET'; 

export const CONTACTS_LOADED = 'CONTACTS_LOADED'; 
export const CONTACTS_ADD_CREATED = 'CONTACTS_ADD_CREATED'; 
export const CONTACTS_SET_UPDATED = 'CONTACTS_SET_UPDATED'; 

export const CONTACT_LOADED = 'CONTACT_LOADED'; 
export const CONTACT_CREATED = 'CONTACT_CREATED';  
export const CONTACT_UPDATED = 'CONTACT_UPDATED'; 
export const CONTACT_RESET = 'CONTACT_RESET'; 

export const FILES_CONTAINER_LOADED = 'FILES_CONTAINER_LOADED'; 
export const FILES_CONTAINER_ADD_CREATED = 'FILES_CONTAINER_ADD_CREATED'; 
export const FILES_CONTAINER_SET_UPDATED = 'FILES_CONTAINER_SET_UPDATED'; 
export const FILES_CONTAINER_SET_DELETED = 'FILES_CONTAINER_SET_DELETED'; 


export const FILE_CONTAINER_LOADED = 'FILE_CONTAINER_LOADED'; 
export const FILE_CONTAINER_CREATED = 'FILE_CONTAINER_CREATED';  
export const FILE_CONTAINER_UPDATED = 'FILE_CONTAINER_UPDATED'; 
export const FILE_CONTAINER_RESET = 'FILE_CONTAINER_RESET'; 

export const FILE_RESET = 'FILE_RESET'; 

export const FILES_LOADED = 'FILES_LOADED'; 
export const FILES_ADD_CREATED = 'FILES_ADD_CREATED'; 
export const FILES_SET_DELETED = 'FILES_SET_DELETED'; 

export const FILE_TYPES_LOADED = 'FILE_TYPES_LOADED'; 

export const PROJECT_CLIENT_STATUSES_RESET = 'PROJECT_CLIENT_STATUSES_RESET'; 
export const PROJECTS_CLIENT_STATUSES_CREATED = 'PROJECTS_CLIENT_STATUSES_CREATED'; 
export const PROJECTS_CLIENT_STATUSES_UPDATED = 'PROJECTS_CLIENT_STATUSES_UPDATED'; 

export const USERS_LOADED = 'USERS_LOADED'; 
export const USERS_ADD_CREATED = 'USERS_ADD_CREATED'; 
export const USERS_SET_UPDATED = 'USERS_SET_UPDATED'; 

export const USER_LOADED = 'USER_LOADED'; 
export const USER_CREATED = 'USER_CREATED';  
export const USER_UPDATED = 'USER_UPDATED'; 
export const USER_RESET = 'USER_RESET'; 

export const USER_LOGIN = 'USER_LOGIN'; 

export const SET_APP_TITLE = 'SET_APP_TITLE';  
export const SET_APP_DESCRIPTION = 'SET_APP_DESCRIPTION';  
export const SET_APP_ERROR = 'SET_APP_ERROR';
export const SET_APP_TOGGOLE_MODAL = 'SET_APP_TOGGOLE_MODAL';
export const SET_APP_PDF_VIEWER = 'SET_APP_PDF_VIEWER';

